### ISSUE TITLE
Enable GC_set_handle_fork(1) for Darwin with GC_incremental on

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#103]
Both single- and multi-threaded modes should be handled.

**Comment by ivmai** [comment]
The issue is resolved (by commit ba2861e) only on multi-threaded builds. Also, the incremental mode is turned off in the child process. See issue #590.

**Comment by ivmai** [comment]
Yes, that's a different issue.

**Comment by catap** [comment]
and doesn't fix https://github.com/sharplispers/ironclad/issues/63 which is expected

**Comment by ivmai** [comment]
> and doesn't fix [sharplispers/ironclad#63](https://github.com/sharplispers/ironclad/issues/63) which is expected

Is there an issue here?

**Comment by catap** [comment]
> > and doesn't fix [sharplispers/ironclad#63](https://github.com/sharplispers/ironclad/issues/63) which is expected
> 
> Is there an issue here?

By some unknown reason when ECL uses clang it leads to random result of hashing, and switching to GCC fixes it.

**Comment by ivmai** [comment]
> Without it I can reproduce random failure like this:
> 0x7ff817e58d14 abort + 123
> 3   libgc.1.dylib                 	       0x10d153eb8 GC_stop_world.cold.1 + 25

I understand. 

> Any plan to release the new version with this changes?

It's planned at the end of Feb. v8.4.0

**Comment by catap** [comment]
> It's planned at the end of Feb. v8.4.0

Do you think I can backport only https://github.com/ivmai/bdwgc/commit/ba2861e70ccbc8ecd4d7611cf5433d30e76f68a1 into last relesead version to increase stability ECL at MacPorts? Is it enough?

**Comment by ivmai** [comment]
> Do you think I can backport only https://github.com/ivmai/bdwgc/commit/ba2861e70ccbc8ecd4d7611cf5433d30e76f68a1 into last relesead version to increase stability ECL at MacPorts? Is it enough?

Initially I though of it as a feature (to enable automatic fork handling by default), but now I see it serves as a fix... Let me check the complexity of backporting to the stable branch.

**Comment by ivmai** [comment]
Backported, please test branch release-8_2.

**Comment by catap** [comment]
I can't reproduce this issue on my laptop anymore on da069190905872d02a832357016008925c9ba3dd.

Run tests via github CI with gc from v8.2.4 and da069190905872d02a832357016008925c9ba3dd. Expected that the first fails, and the second one passes. ETA couple of hours.

**Comment by catap** [comment]
Confirmed with GitHub CI. Fails with v8.2.4 and works with stable from da069190905872d02a832357016008925c9ba3dd

**Comment by catap** [comment]
Can you make 8.2.5 release with this huge improvement for macOS?

**Comment by ivmai** [comment]
> Can you make 8.2.5 release with this huge improvement for macOS?

v8.2.6. I will think of.

**Comment by catap** [comment]
why v8.2.6? I haven't see v8.2.5 here https://github.com/ivmai/bdwgc/tags

**Comment by ivmai** [comment]
> why v8.2.6? I haven't see v8.2.5 here https://github.com/ivmai/bdwgc/tags

All micro numbers are even ;) just a convention.

**Comment by ivmai** [comment]
> Can you make 8.2.5 release with this huge improvement for macOS?

I want to fix another ancient bug on macOS before the release - issue #178

**Comment by catap** [comment]
Fair enough.

**Comment by ivmai** [comment]
> Can you make 8.2.5 release with this huge improvement for macOS?

Released: https://github.com/ivmai/bdwgc/releases/tag/v8.2.6
