### ISSUE TITLE
Guile process aborted when recovering from out-of-memory

### ISSUE THREAD

**Issue by flatwhatson** [ivmai/bdwgc#353]
Greetings!

We have a failing unit test for Guile called `test-out-of-memory` which sets RLIMIT_AS to a low value, tries to allocate too much memory, and then calls `GC_gcollect_and_unmap` to try and recover.  This should unmap some unused blocks and allow the process to continue.

Instead, the process is killed with SIGABRT from `GC_unmap`:
<pre>
Thread 1 "guile" received signal SIGABRT, Aborted.
#0  0x00007ffff7891aba in raise () from /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libc.so.6
#1  0x00007ffff7892bf5 in abort () from /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libc.so.6
#2  0x00007ffff7e194ee in GC_unmap (start=<optimized out>, bytes=<optimized out>) at extra/../os_dep.c:2576
#3  0x00007ffff7e195d1 in GC_unmap_old () at extra/../allchblk.c:419
#4  0x00007ffff7e20882 in GC_unmap_old () at extra/../allchblk.c:404
#5  GC_finish_collection () at extra/../alloc.c:1115
#6  0x00007ffff7e20cf5 in GC_try_to_collect_inner (stop_func=0x7ffff7e0ea70 <GC_never_stop_func>) at extra/../alloc.c:553
#7  0x00007ffff7e231cf in GC_try_to_collect_general (stop_func=stop_func@entry=0x7ffff7e0ea70 <GC_never_stop_func>, force_unmap=force_unmap@entry=1) at extra/../alloc.c:1161
#8  0x00007ffff7e23322 in GC_gcollect_and_unmap () at extra/../alloc.c:1197
#9  0x00007ffff7ed1d5f in scm_gc_after_nonlocal_exit () at gc.c:116
</pre>

A trace shows that this is because `mmap(PROT_NONE)` returns ENOMEM:
<pre>
mmap(0x7f9c5fb25000, 134348800, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "GC Warning: Failed to expand hea"..., 53) = 53
mmap(0x7f9c5fb25000, 134217728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "GC Warning: Failed to expand hea"..., 53) = 53
write(2, "GC Warning: Out of Memory! Heap "..., 61) = 61
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "error creating finalization thre"..., 59) = 59
mmap(0x7f9c5fefa000, 557056, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "mmap(PROT_NONE) failed", 22)  = 22
write(2, "\n", 1)
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2407249, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
</pre>

There is an alternative code path in `GC_unmap` using `mprotect(PROT_NONE)` on some platforms.  Testing with a libgc patched to use this path on Linux, the operation succeeds:
<pre>
mmap(0x7f1f47696000, 134348800, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "GC Warning: Failed to expand hea"..., 53) = 53
mmap(0x7f1f47696000, 134217728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "GC Warning: Failed to expand hea"..., 53) = 53
write(2, "GC Warning: Out of Memory! Heap "..., 61) = 61
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "error creating finalization thre"..., 59) = 59
mprotect(0x7f1f47a6b000, 557056, PROT_NONE) = 0
...
</pre>

This bug has shown up in the wild in Guix: https://issues.guix.gnu.org/40525
Also the test is being skipped on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969707

Patch for 8.0.4: https://github.com/flatwhatson/bdwgc/commit/414914ba41e053b17bf7a699a9e740ba6b91bdd2
Patch for master: https://github.com/flatwhatson/bdwgc/commit/419d7433f047e93991e90a1ba792e2a25dec5004

**Comment by flatwhatson** [comment]
The behaviour of `mmap()` failing in this case is documented in `man getrlimit`:
> RLIMIT_AS
> This  is the maximum size of the process's virtual memory (address space).  The limit is specified in bytes, and is rounded down to the system page size.  This limit affects calls to brk(2), mmap(2), and mremap(2), which fail with the error ENOMEM upon exceeding this limit.

**Comment by ivmai** [comment]
Please check if it is reproducible on recent master. I guess it should be solved in #324

**Comment by flatwhatson** [comment]
Yes, this is still reproducible on master.  I don't think it's directly related to #324.

**Comment by ivmai** [comment]
Okay, I will fix it as you proposed (at least in v8.2.0)
